# Generated by Django 5.0.1 on 2024-02-07 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank='True', default=None, null='True', on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
            preserve_default='True',
        ),
    ]
