# Generated by Django 4.2.9 on 2024-02-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
