# Generated by Django 5.0.1 on 2024-02-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_username_review_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
