# Generated by Django 5.0.1 on 2024-02-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_review_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='userreview',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
